---
galaxy_info:
  role_name: ubuntu_26_kernel_hardening
  namespace: peedy2495
  author: peedy2495
  description: Combine BSI and CIS Ubuntu 26 kernel policies.
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - bsi
    - cis
    - ubuntu
    - kernel
    - security
dependencies: []
