---
- name: Apply the CIS Ubuntu 26 kernel module policy
  ansible.builtin.include_role:
    name: peedy2495.syshardening.cis_ubuntu_26_kernel_module

- name: Apply the CIS Ubuntu 26 GRUB policy
  ansible.builtin.include_role:
    name: peedy2495.syshardening.cis_ubuntu_26_grub

- name: Apply the CIS Ubuntu 26 AppArmor policy
  ansible.builtin.include_role:
    name: peedy2495.syshardening.cis_ubuntu_26_apparmor

- name: Apply the CIS Ubuntu 26 core dump policy
  ansible.builtin.include_role:
    name: peedy2495.syshardening.cis_ubuntu_26_core_dump
