---
galaxy_info:
  role_name: bsi_all
  namespace: peedy2495
  author: peedy2495
  description: Dispatch platform-independent BSI policy roles.
  min_ansible_version: "2.14"
  galaxy_tags:
    - bsi
    - grundschutz
    - security
dependencies: []
